language: objective-c
osx_image: xcode8
cache:
  bundler: true
  directories:
    - Carthage
    - $HOME/Library/Caches/carthage_cache
# before_install:
#- brew update
install:
- bundle
- carthage_cache install -b slate-cache || ((travis_wait 30 carthage bootstrap --platform iOS --no-use-binaries) && carthage_cache publish -b slate-cache) #--verbose
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Slate'
script:
- set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project ./Slate.xcodeproj -scheme Slate  -sdk iphonesimulator -destination 'name=iPhone SE' build test | xcpretty
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/689437210f0e8a62afde
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
